spring.application.name=WorkorderDwnld
server.port=8989
# Datasource DEV
spring.datasource.url=jdbc:oracle:thin:@dwdb01.cuuuvi7xhm1i.ap-south-1.rds.amazonaws.com:1521:dbstagin
spring.datasource.username=PROD_SOLAR
spring.datasource.password=MagelTyala%$&^

#file.upload.path=/data

file.upload.path=D:\\files
#file.upload.path=file.upload.path=/data/tomcat-9.0.56-dms/logs
